// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSMzcosYWIqp8qGbMM9NdPlCm8ucLoSMw',
    appId: '1:932295453468:web:3c3bcb7304294f7e15a8d9',
    messagingSenderId: '932295453468',
    projectId: 'chatgpt-app-66c8a',
    authDomain: 'chatgpt-app-66c8a.firebaseapp.com',
    storageBucket: 'chatgpt-app-66c8a.firebasestorage.app',
    measurementId: 'G-PX004REYPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQ718tHRrYGURnGQ-uhNO5lMz6Szc0MQ',
    appId: '1:932295453468:android:9e9e27c2f73c7f2315a8d9',
    messagingSenderId: '932295453468',
    projectId: 'chatgpt-app-66c8a',
    storageBucket: 'chatgpt-app-66c8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBumfhpMkCjaDfwLaryBUfpOfSKqlaURsc',
    appId: '1:932295453468:ios:a02a52c129f82ccc15a8d9',
    messagingSenderId: '932295453468',
    projectId: 'chatgpt-app-66c8a',
    storageBucket: 'chatgpt-app-66c8a.firebasestorage.app',
    iosBundleId: 'com.example.chatgptApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBumfhpMkCjaDfwLaryBUfpOfSKqlaURsc',
    appId: '1:932295453468:ios:a02a52c129f82ccc15a8d9',
    messagingSenderId: '932295453468',
    projectId: 'chatgpt-app-66c8a',
    storageBucket: 'chatgpt-app-66c8a.firebasestorage.app',
    iosBundleId: 'com.example.chatgptApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSMzcosYWIqp8qGbMM9NdPlCm8ucLoSMw',
    appId: '1:932295453468:web:eb16c562a6a5972b15a8d9',
    messagingSenderId: '932295453468',
    projectId: 'chatgpt-app-66c8a',
    authDomain: 'chatgpt-app-66c8a.firebaseapp.com',
    storageBucket: 'chatgpt-app-66c8a.firebasestorage.app',
    measurementId: 'G-6RMRKPWK8F',
  );
}
